# /boot/loader.conf — GovechoBSD
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
zfs_load="YES"
vfs.root.mountfrom="zfs:govechoOS/zroot/ROOT/default"
linux_load="YES"
fdescfs_load="YES"
tmpfs_load="YES"
