# /etc/rc.conf — GovechoBSD (автор ZHBR-228, MIT)
hostname="govechoos"
zfs_enable="YES"
linux_enable="YES"            # Linuxulator: запуск flatpak/snap из Debian-мира
sshd_enable="YES"
dbus_enable="YES"             # нужен GNOME
gdm_enable="YES"              # GNOME Display Manager
moused_enable="YES"
powerd_enable="YES"
ifconfig_DEFAULT="SYNCDHCP DHCP"
sendmail_submit_enable="NO"
performance_cputypes="NONE"
