# /etc/sysctl.conf — тюнинг ядра FreeBSD под GNOME+ZFS
security.bsd.unprivileged_proc_debug=0
kern.randompid=1000
net.inet.tcp.functions_default=bbr        # TCP BBR — быстрая сеть
vfs.zfs.arc_max=17179869184               # 16 GiB кэш ZFS
kern.corefile=/var/core/%N.core
